name: ssbi-group-project
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - jupyterlab=4.6
  - ipykernel=7
  - numpy=2.5
  - pandas=2.3
  - scipy=1.18
  - matplotlib=3.11
  - seaborn=0.13
  - scikit-learn=1.9
  - umap-learn=0.5
  - scanpy=1.12
  - python-igraph=1.0
  - leidenalg=0.12
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - flowkit==1.3.2
      - torch==2.14.0+cpu
